metric: COCO
num_classes: 10

TrainDataset:
  !COCODataSet
    image_dir: VisDrone2019-DET-train
    anno_path: train_info.json
    # Fill in your own path
    dataset_dir: dataset/visdrone
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: VisDrone2019-DET-val
    anno_path: val_info.json
    # Fill in your own path
    dataset_dir: dataset/visdrone
    allow_empty: true

TestDataset:
  !ImageFolder
    image_dir: VisDrone2019-DET-test_dev
    anno_path: test_dev.json
    # Fill in your own path
    dataset_dir: dataset/visdrone
